version: '2'

services:

  ## --------------------------------------------
  ## | Front Reverse Proxy/Balancer 
  ## --------------------------------------------
  web-server:
    build:
      context: ./.docker-compose
      dockerfile: Dockerfile
    image: papion_web-frontproxy
    ports:
     - "80:80"
    environment:
     ## ping this host and wait until its reply before running nginx
     - WAIT_FOR=papion_web-server
    volumes:
     - ./.docker-compose/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./.docker-compose/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
     - ./.docker-compose/.htpasswd:/etc/nginx/.htpasswd
     - ./www/:/usr/share/nginx/html:ro
    networks:
      - front-network
networks:
  front-network:
