# --------------------------------------------------------------------
# | 
# | @depends https://github.com/E1101/docker-nginx
# |
## TODO using official base images
FROM payam/nginx

MAINTAINER Payam Naderi <naderi.payam@gmail.com>

